### ISSUE TITLE
32/64 bit binary running issues

### ISSUE THREAD

**Issue by lifeasageek** [ohjeongwook/DarunGrim#12]
IDA supports 32/64 bit binaries with different executables, idag.exe and idag64.exe, but DG simply tries to run idag.exe for both 32/64bit binaries.
Though DG knows the supporting architecture of the binary now, still DG needs to run an appropriate one according to the supporting architecture of the binary.

**Comment by ohjeongwook** [comment]
This is fixed with latest DarunGrim release.
