### ISSUE TITLE
The pre-built binary download link is not working

### ISSUE THREAD

**Issue by s4n7h0** [ohjeongwook/DarunGrim#18]
The download link is not working due to warning from google "this file is infected with a virus". Wouldn't it be create a release section with final compiled binaries ?

**Comment by vgturtle127** [comment]
@s4n7h0 We are working on it, I just have been busy. We apologize for the lack of binaries. I promise I haven't forgotten. :smile:

**Comment by darungrim** [comment]
I just transferred the file to new release section for now.

https://github.com/ohjeongwook/DarunGrim/releases/tag/4

**Comment by vgturtle127** [comment]
@darungrim Thanks, buddy! I am going to be more active soon, I have been having issues with Windows 10.
