### ISSUE TITLE
Don't run DarunGrim2 Plugin 

### ISSUE THREAD

**Issue by codeengn** [ohjeongwook/DarunGrim#9]
After selecting a series of menu entries to open IDA as the following :
List  >MS10-001  >Windows XP Service Pack 2 and Windows XP Service Pack 3  >fontsub.dll   [Open IDA] 

and then selecting the dfg file after running DarunGrim2 generates the following message, but the changes are not reflected in IDA.
Is a Gui Diff window supposed to pop up like the earlier versions of Darumgrim2?

###
Start DarunGrim2 Plugin 
Opening Database [C:\CodeEngn\Tools\DarunGrim3\Output\1708_3324.dgf] 
Retrieving File Information 
Sending Analyzed Information 
Sent All Analysis Informations 
DarunGrim2 Analysis Finished 1.953 sec

**Comment by ohjeongwook** [comment]
The DarunGrim server is deprecated with newer DarunGrim and Qt GUI is used now. I suppose the issue is fixed.
